services:
  app:
    build: .
    expose:
      - 8000
    networks:
      - main_network
    environment:
      DEBUG: False
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media

  nginx:
    image: nginx:alpine
    command: nginx -g "daemon off;"
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./media:/var/www/html/media
    ports:
      - "80:80"
    networks:
      - main_network
    depends_on:
      - app



networks:
  main_network:
    driver: bridge
